---
- name: Check if brew is installed
  shell: |
    export PATH=/usr/local/bin:/opt/homebrew/bin:$PATH
    command -v brew
  args:
    executable: /bin/bash
  register: does_brew_exist
  ignore_errors: true
  changed_when: false

- name: Install brew
  command: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  when: does_brew_exist.rc

- name: Install node_exporter
  community.general.homebrew:
    name: node_exporter
    state: present
  become: false

- name: Copy the node_exporter launchd service file
  template:
    src: homebrew.mxcl.node_exporter.plist
    dest: /Library/LaunchDaemons/homebrew.mxcl.node_exporter.plist
    owner: root
    group: "{{ _node_exporter_root_group }}"
    mode: 0644
  notify: restart node_exporter osx homebrew

- name: Flush handlers
  meta: flush_handlers

- name: End the play for hosts that run macOS arm64
  ansible.builtin.meta: end_host
  when:
    - ansible_distribution == 'MacOSX'
    - ansible_architecture == 'arm64'
