---
- name: Create node_exporter binary and config directory
  ansible.windows.win_file:
    path: "{{ node_exporter_binary_install_dir_windows }}"
    state: directory


- name: Set default _node_exporter_web_config
  ansible.builtin.set_fact:
    _node_exporter_web_config: ""

- name: A windows block
  when:
    ( node_exporter_tls_server_config | length > 0 ) or
    ( node_exporter_http_server_config | length > 0 ) or
    ( node_exporter_basic_auth_users | length > 0 )
  block:
    - name: Set _node_exporter_web_config
      ansible.builtin.set_fact:
        _node_exporter_web_config: "{{ node_exporter_binary_install_dir_windows }}\\web.config.yaml"

    - name: Copy the windows_exporter web config file
      ansible.builtin.template:
        src: config.yaml.j2
        dest: "{{ _node_exporter_web_config }}"
      notify: Restart windows_exporter

- name: Copy the windows_exporter config file
  ansible.builtin.template:
    src: windows.config.yaml.j2
    dest: "{{ node_exporter_binary_install_dir_windows }}\\config.yaml"
  notify: Restart windows_exporter

- name: Create textfile collector dir
  ansible.windows.win_file:
    path: "{{ node_exporter_textfile_dir_windows }}"
    state: directory
    recurse: true
  when: node_exporter_textfile_dir_windows | length > 0
