---
- name: Create the node_exporter group
  become: true
  ansible.builtin.group:
    name: "{{ node_exporter_system_group }}"
    state: present
    system: true
  when:
    - ansible_system != 'Win32NT'
    - node_exporter_system_group != "root"

- name: Create the node_exporter user
  become: true
  ansible.builtin.user:
    name: "{{ node_exporter_system_user }}"
    groups: "{{ node_exporter_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false
    home: /
  when:
    - ansible_system != 'Win32NT'
    - node_exporter_system_user != "root"

- name: Check if node_exporter_binary_install_dir directory exists
  become: true
  ansible.builtin.stat:
    path: "{{ node_exporter_binary_install_dir }}"
  register: install_dir_check
  when:
    - ansible_system != 'Win32NT'

- name: Create node_exporter_binary_install_dir
  become: true
  ansible.builtin.file:
    path: "{{ node_exporter_binary_install_dir }}"
    state: directory
    owner: root
    group: "{{ node_exporter_root_group }}"
    mode: u+rwX,g+rwX,o=rX
  when:
    - ansible_system != 'Win32NT'
    - not install_dir_check.stat.exists

- name: Make tmp dir - Windows
  become: true
  ansible.windows.win_file:
    path: "C:\\tmp"
    state: directory
  when:
    - not ansible_check_mode
    - ansible_system == 'Win32NT'

- name: Installer block
  when:
    - node_exporter_binary_local_dir | length == 0
  block:
    - name: Download node_exporter binary to local folder - Windows
      become: false
      ansible.builtin.get_url:
        url: "https://github.com/prometheus-community/windows_exporter/releases/download/v{{ node_exporter_version_windows }}/windows_exporter-{{ node_exporter_version_windows
          }}-{{ go_arch }}.msi"
        dest: "/tmp/windows_exporter-{{ node_exporter_version_windows }}-{{ go_arch }}.msi"
        checksum: "sha256:{{ node_exporter_checksum_windows }}"
        mode: "0644"
      register: _download_binary_windows
      until: _download_binary_windows is succeeded
      retries: 5
      delay: 2
      delegate_to: localhost
      check_mode: false
      when:
        - ansible_system == 'Win32NT'

    - name: Download node_exporter binary to local folder - Linux
      become: false
      ansible.builtin.get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.{{ ansible_system
          | lower }}-{{ go_arch }}.tar.gz"
        dest: "/tmp/node_exporter-{{ node_exporter_version }}.{{ ansible_system | lower }}-{{ go_arch }}.tar.gz"
        checksum: "sha256:{{ node_exporter_checksum }}"
        mode: "0644"
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      delegate_to: localhost
      check_mode: false
      when:
        - ansible_system != 'Win32NT'

    - name: Unpack node_exporter binary
      become: false
      ansible.builtin.unarchive:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.{{ ansible_system | lower }}-{{ go_arch }}.tar.gz"
        dest: "/tmp"
        creates: "/tmp/node_exporter-{{ node_exporter_version }}.{{ ansible_system | lower }}-{{ go_arch }}/node_exporter"
      delegate_to: localhost
      check_mode: false
      when:
        - ansible_system != 'Win32NT'

    - name: Propagate windows_exporter installer - Windows
      ansible.windows.win_copy:
        src: "/tmp/windows_exporter-{{ node_exporter_version_windows }}-{{ go_arch }}.msi"
        dest: "C:\\tmp\\windows_exporter-{{ node_exporter_version_windows }}-{{ go_arch }}.msi"
        mode: "0755"
        owner: root
      when:
        - not ansible_check_mode
        - ansible_system == 'Win32NT'

    - name: Propagate node_exporter binaries
      become: true
      ansible.builtin.copy:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.{{ ansible_system | lower }}-{{ go_arch }}/node_exporter"
        dest: "{{ node_exporter_binary_install_dir }}/node_exporter"
        mode: "0755"
        owner: root
      notify: Restart node_exporter
      when:
        - not ansible_check_mode
        - ansible_system != 'Win32NT'

    # 2025: the arguments have changed since the last time.
    - name: Install Windows exporter
      ansible.windows.win_package:
        path: "C:\\tmp\\windows_exporter-{{ node_exporter_version_windows }}-{{ go_arch }}.msi"
        arguments: 'LISTEN_PORT=9100 ADDLOCAL=FirewallException CONFIG_FILE="C:\Program Files\windows_exporter\config.yaml"'
        state: present
      when:
        - not ansible_check_mode
        - ansible_system == 'Win32NT'
      notify: Restart windows_exporter

- name: Propagate locally distributed windows installer
  ansible.builtin.copy:
    src: "{{ node_exporter_local_installer }}"
    dest: "C:\\tmp\\windows_exporter.msi"
    mode: "0755"
    owner: root
    group: "{{ node_exporter_root_group }}"
  when:
    - ansible_system == 'Win32NT'
    - node_exporter_local_installer | length > 0
    - not ansible_check_mode

- name: Install locally distributed Windows exporter
  ansible.windows.win_package:
    path: "C:\\tmp\\windows_exporter.msi"
    arguments: 'EXTRA_FLAGS="--config.file ""C:\Program Files\windows_exporter\config.yaml"""'
    state: present
  when:
    - ansible_system == 'Win32NT'
    - node_exporter_local_installer | length > 0
    - not ansible_check_mode
  notify: Restart windows_exporter

- name: Propagate locally distributed node_exporter binary
  become: true
  ansible.builtin.copy:
    src: "{{ node_exporter_binary_local_dir }}/node_exporter"
    dest: "{{ node_exporter_binary_install_dir }}/node_exporter"
    mode: "0755"
    owner: root
    group: "{{ node_exporter_root_group }}"
  when:
    - ansible_system != 'Win32NT'
    - node_exporter_binary_local_dir | length > 0
  notify: Restart node_exporter
