---
- name: Client FreeBSD
  ansible.builtin.include_tasks:
    file: client_freebsd.yml
  when:
    - ansible_system == 'FreeBSD'

- name: Client MacOS
  ansible.builtin.include_tasks:
    file: client_macos_m1.yml
  when:
    - ansible_distribution == 'MacOSX'
    - ansible_architecture == 'arm64'

- name: Preflight
  ansible.builtin.include_tasks:
    file: preflight.yml
  tags:
    - node_exporter_install
    - node_exporter_configure
    - node_exporter_run

- name: Configure Windows
  ansible.builtin.include_tasks:
    file: configure_windows.yml
  when:
    - ansible_system == 'Win32NT'
  tags:
    - node_exporter_configure

- name: Install
  ansible.builtin.include_tasks:
    file: install.yml
  when:
    ( ( not __node_exporter_is_installed.stat.exists ) or
    ( (__node_exporter_current_version_output.stderr_lines | length > 0) and (__node_exporter_current_version_output.stderr_lines[0].split(" ")[2] != node_exporter_version) ) or
    ( (__node_exporter_current_version_output.stdout_lines | length > 0) and (__node_exporter_current_version_output.stdout_lines[0].split(" ")[2] != node_exporter_version) ) or
    ( node_exporter_binary_local_dir | length > 0 ) ) and
    ansible_system != 'Win32NT'
  tags:
    - node_exporter_install

- name: Windows Install
  ansible.builtin.include_tasks:
    file: install.yml
  when:
    ( ( not __node_exporter_is_installed.stat.exists ) or
    ( (__node_exporter_current_version_output.stderr_lines | length > 0) and (__node_exporter_current_version_output.stderr_lines[0].split(" ")[2] != node_exporter_version_windows) ) or
    ( (__node_exporter_current_version_output.stdout_lines | length > 0) and (__node_exporter_current_version_output.stdout_lines[0].split(" ")[2] != node_exporter_version_windows) ) or
    ( node_exporter_binary_local_dir | length > 0 ) ) and
    ansible_system == 'Win32NT'
  tags:
    - node_exporter_install

- name: SELinux
  ansible.builtin.include_role:
    name: prometheus.prometheus._common
    tasks_from: selinux.yml
  vars:
    _common_selinux_port: "{{ node_exporter_web_listen_address | urlsplit('port') }}"
  when:
    - ansible_system == 'Linux'
    - ansible_facts['selinux'].status == "enabled"
  tags:
    - node_exporter_configure

- name: Configure
  ansible.builtin.include_tasks:
    file: configure.yml
  tags:
    - node_exporter_configure
  when:
    - ansible_system != 'Win32NT'

- name: Ensure Node Exporter is enabled on boot
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: node_exporter
    enabled: true
    state: started
  when:
    - not ansible_check_mode
    - ansible_system == 'Linux'
  tags:
    - node_exporter_run

- name: Ensure Node Exporter is started
  become: true
  ansible.builtin.command: |
    launchctl load /Library/LaunchDaemons/cloudalchemy.mxcl.node_exporter.plist
  changed_when: false
  when:
    - ansible_distribution == 'MacOSX'
    - not ansible_check_mode
