---
version: 2.1

executors:
  python:
    docker:
      - image: cimg/python:3.10
  python_large:
    docker:
      - image: cimg/python:3.9
    resource_class: large
  publisher:
    docker:
      - image: quay.io/cloudalchemy/publisher:latest

jobs:
  lint:
    executor: python
    steps:
      - checkout
      - run: pip install ansible ansible-lint yamllint flake8
      - run: ansible-lint
      - run: yamllint .
      - run: flake8

  test:
    executor: python_large
    parameters:
      ansible:
        type: string
      scenario:
        type: string
    steps:
      - checkout
      - setup_remote_docker
      - run: pip install "ansible~=<< parameters.ansible >>.0"
      - run: pip install -r test-requirements.txt
      - run:
          no_output_timeout: 60m
          command: |
            if [[ -n "${CIRCLE_PULL_REQUEST}" ]] && [[ '<< parameters.scenario >>' == 'latest' ]]; then
              echo 'Not running latest on PR'
            else
              molecule test -s '<< parameters.scenario >>' --destroy always
              # molecule  --debug dependency -s '<< parameters.scenario >>'
              # molecule  --debug lint -s '<< parameters.scenario >>'
              # molecule  --debug cleanup -s '<< parameters.scenario >>'
              # molecule  --debug destroy -s '<< parameters.scenario >>'
              # molecule  --debug syntax -s '<< parameters.scenario >>'
              # molecule  --debug create -s '<< parameters.scenario >>'
              # molecule  --debug prepare -s '<< parameters.scenario >>'
              # molecule  --debug converge -s '<< parameters.scenario >>'
              # molecule  --debug idempotence -s '<< parameters.scenario >>'
              # molecule  --debug verify -s '<< parameters.scenario >>'
              # molecule  --debug cleanup -s '<< parameters.scenario >>'
              # molecule  --debug destroy -s '<< parameters.scenario >>'
            fi
  release:
    executor: publisher
    steps:
      - checkout
      - run: |
          PROJECT_USERNAME="${CIRCLE_PROJECT_USERNAME}" \
          PROJECT_REPONAME="${CIRCLE_PROJECT_REPONAME}" \
          create_release

  galaxy:
    executor: python
    steps:
      - checkout
      - run: pip install ansible
      - run: ansible-galaxy role import --token "${GALAXY_TOKEN}" "${CIRCLE_PROJECT_USERNAME}" "${CIRCLE_PROJECT_REPONAME}"

workflows:
  version: 2
  molecule:
    jobs:
      - lint:
          filters:
            tags:
              only: /.*/
      - test:
          matrix:
            parameters:
              ansible:
                - "2.9"
                - "2.10"
                - "4.10"
                - "5.1"
              scenario:
                - default
                - alternative
                - latest
          filters:
            tags:
              only: /.*/
      - release:
          context: release
          requires:
            - lint
            - test
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
      - galaxy:
          context: galaxy
          requires:
            - lint
            - test
            - release
          filters:
            branches:
              only: master
