---
- name: Restart node_exporter
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: node_exporter
    state: restarted
  when:
    - not ansible_check_mode
    - ansible_system == 'Linux'

- name: Restart node_exporter osx
  ansible.builtin.shell: |
    /bin/launchctl unload /Library/LaunchDaemons/cloudalchemy.mxcl.node_exporter.plist
    /usr/bin/pkill node_exporter
    /bin/launchctl load /Library/LaunchDaemons/cloudalchemy.mxcl.node_exporter.plist
  become: true
  changed_when: false
  when:
    - not ansible_check_mode
    - ansible_distribution == 'MacOSX'

- name: Restart node_exporter osx homebrew
  ansible.builtin.shell: |
    /bin/launchctl unload /Library/LaunchDaemons/homebrew.mxcl.node_exporter.plist
    /usr/bin/pkill node_exporter
    /bin/launchctl load /Library/LaunchDaemons/homebrew.mxcl.node_exporter.plist
  become: true
  changed_when: false
  when:
    - not ansible_check_mode
    - ansible_distribution == 'MacOSX'

- name: Restart windows_exporter
  ansible.windows.win_service:
    name: windows_exporter
    state: restarted
  when:
    - not ansible_check_mode
    - ansible_system == 'Win32NT'
