---
name: macos ci
'on':
  pull_request:
  push:
    branches:
      - master
      - develop
      - feature/*

jobs:
  macos:
    name: macos
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include: 
          - os: macos-10.15
            ansible_python_interpreter: /usr/local/bin/python3
        scenario:
          - latest
          - default
          - alternative
        ansible_version:
          - "2.9"
          - "2.10"
          - "4.10"
          - "5.1"

    steps:
      - name: Check out the codebase
        uses: actions/checkout@v2

      - name: Check pip packages
        run: sudo pip3 list

      - name: Install test dependencies
        run: sudo pip3 install "ansible~=${{ matrix.ansible_version }}.0"

      - name: Set up the test environment
        run: |
          cp tests/test-inventory ./test-inventory
          cp tests/ansible.cfg ./ansible.cfg
          sudo pip3 install -r test-requirements.txt
          mkdir -p /Users/runner/.ansible/roles
          ln -s $GITHUB_WORKSPACE /Users/runner/.ansible/roles/cloudalchemy.node_exporter

      - name: Test the playbook's syntax
        run: |
          ansible-playbook -e "ansible_python_interpreter=${{ matrix.ansible_python_interpreter }}"  molecule/${{ matrix.scenario }}/playbook.yml --syntax-check

      - name: Run the prepare playbook
        run: |
          export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
          ansible-playbook -vvv -e "ansible_python_interpreter=${{ matrix.ansible_python_interpreter }}" molecule/${{ matrix.scenario }}/prepare.yml

      - name: Run the playbook
        run: |
          export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
          ansible-playbook -vvv -e "ansible_python_interpreter=${{ matrix.ansible_python_interpreter }}" molecule/${{ matrix.scenario }}/playbook.yml
        env:
          ANSIBLE_FORCE_COLOR: '1'

      - name: Test the results
        run: |
          export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
          ansible-playbook tests/tests_macos.yml
        env:
          ANSIBLE_FORCE_COLOR: '1'

      - name: Idempotence check
        run: |
          idempotence=$(mktemp)
          export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES
          ansible-playbook molecule/${{ matrix.scenario }}/playbook.yml | tee -a ${idempotence}
          tail ${idempotence} | grep -q 'changed=0.*failed=0' && (echo 'Idempotence test: pass' && exit 0) || (echo 'Idempotence test: fail' && exit 1)
        env:
          ANSIBLE_FORCE_COLOR: '1'
